# Uncomment this line to define a global platform for your project
 platform :ios, '9.0'

target 'StoreSearch' do
pod 'AFNetworking', '2.6.3'
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for StoreSearch

  target 'StoreSearchTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StoreSearchUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
